# see https://github.com/BaileyJM02/markdown-to-pdf
# CANNOT DO INLINE LATEX :(

name: Testing
on: 
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ github.token }}

# run in parallel
jobs:
  CPP_TESTS:
    name: C++ Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: C++ Tests
        working-directory: c++/tests/
        run: |
          chmod +x ./test.sh
          ./test.sh
  PYTHON_TESTS:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: execute python tests
        working-directory: python/tests/
        run: |
          chmod +x ./test.sh
          ./test.sh

