# see https://github.com/BaileyJM02/markdown-to-pdf
# CANNOT DO INLINE LATEX :(

name: Test C++
on: 
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  CPP_TESTS:
    name: Test C++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: C++ Tests
        working-directory: c++/tests/
        run: |
          gcc --version
          chmod +x ./test.sh
          ./test.sh
